tomcat_home: "{{ ansible_env.HOME }}/tomcat"
tomcat_base: "{{ ansible_env.HOME }}/tomcat_instances"
tomcat_version: '8.0.42'
tomcat_tgz: "apache-tomcat-{{ tomcat_version }}.tar.gz"
tomcat_mirror: http://archive.apache.org/dist/tomcat
tomcat_download_url: "{{ tomcat_mirror }}/tomcat-{{ tomcat_version[:1] }}/v{{ tomcat_version }}/bin/{{ tomcat_tgz }}"

downloads: "{{ playbook_dir }}/downloads"