---
# defaults file for haproxy_pablo
#
#
haproxy_user: 'vagrant'
haproxy_group: 'vagrant'
haproxy_mode: 'http'
haproxy_chroot: '/var/lib/haproxy'

#Frontend settings
haproxy_bind_address: '*'
haproxy_bind_port: '8080'

#Backend settings
haproxy_balance_mode: 'roundrobin'

#List of backend servers
haproxy_servers:
        - name: server1
          address: 192.168.10.2:8080
        - name: server2
          address: 192.168.10.3:8080
