- name: Create httpd_root and httpd_src
  file:
    dest: "{{ item }}"
    state: directory
  with_items:
    - "{{ httpd_root }}"
    - "{{ httpd_src }}"

- name: Download httpd dependencies
  run_once: true
  local_action: get_url
  args:
    url: "{{ item }}"
    dest: "{{ downloads_tmp }}"
  with_items:
    - "{{ apr_download_url }}"
    - "{{ apr_util_download_url }}"
    - "{{ pcre_download_url }}"
    - "{{ httpd_download_url }}"

- name: Unarchive dependencies in remote host
  unarchive:
    src: "{{ downloads_tmp }}/{{ item }}"
    dest: "{{ httpd_src }}"
  with_items:
    - "{{ apr_filename }}"
    - "{{ apr_util_filename }}"
    - "{{ pcre_filename }}"
    - "{{ httpd_filename }}"

- name: Install apr
  command: "{{ item }}"
  args:
    chdir: "{{ httpd_src }}/{{ apr_filename_unarchive }}"
  async: 600
  poll: 10
  with_items:
    - "./configure --prefix={{ apr_install_base }}"
    - "make"
    - "make install"
    - "make clean"
    
- name: Install apr_util
  command: "{{ item }}"
  args:
    chdir: "{{ httpd_src }}/{{ apr_util_filename_unarchive }}"
  async: 600
  poll: 10
  with_items:
    - "./configure --prefix={{ apr_util_install_base }} --with-apr={{ apr_install_base }}"
    - "make"
    - "make install"
    - "make clean"

- name: Install pcre
  command: "{{ item }}"
  args:
    chdir: "{{ httpd_src }}/{{ pcre_filename_unarchive }}"
  async: 600
  poll: 10
  with_items:
    - "./configure --prefix={{ pcre_install_base }}"
    - "make"
    - "make install"
    - "make clean"

- name: Install httpd
  command: "{{ item }}"
  args:
    chdir: "{{ httpd_src }}/{{ httpd_filename_unarchive }}"
  async: 600
  poll: 10
  with_items:
    - ./configure --prefix={{ httpd_root }} --enable-mpms-shared=all --with-apr={{ apr_install_base }} --with-apr-util={{ apr_util_install_base }} --with-pcre={{ pcre_install_base }}
    - /usr/bin/make
    - /usr/bin/make install
    - /usr/bin/make clean
