---
- name: Set facts for backend servers to register
  set_fact:
    catalog_backend: "{{ catalog_backend }}"
    restricted_backend: "{{ restricted_backend }}"

- name: Create ACL for each service+collection
  lineinfile:
    path: "{{ haproxy_conf }}"
    line: "\tacl {{ item.0.path | replace('/','-') }} path_beg /thredds/{{ item.1 }}/{{ item.0.path }}"
    insertafter: "option forwardfor"
  with_subelements:
    - "{{ collections }}"
    - services

- name: Create ACLs for main catalog & restrictedAccess
  lineinfile:
    path: "{{ haproxy_conf }}"
    line: "\tacl {{ item }} path_beg /thredds/{{ item }}"
    insertafter: "option forwardfor"
  with_items:
    - "{{ catalog_backend }}"
    - "{{ restricted_backend }}"

- name: Create ACL for /thredds uri (which redirects to main catalog)
  lineinfile:
    path: "{{ haproxy_conf }}"
    line: "\t acl {{ catalog_backend }} path_end thredds"
    insertafter: "option forwardfor"

- name: Define collections' ACL rule behaviour
  lineinfile: 
    path: "{{ haproxy_conf }}"
    line: "\tuse_backend {{ item.path | replace('/', '-') }} if {{ item.path | replace('/', '-') }}"
    insertbefore: "backend .*"
    firstmatch: True
  with_items: "{{ collections }}"

- name: Define main catalog's & restrictedAccess ACLs rule behaviour
  lineinfile:
    path: "{{ haproxy_conf }}"
    line: "\tuse_backend {{ item }} if {{ item }}"
  with_items:
    - "{{ catalog_backend }}"
    - "{{ restricted_backend }}"

- name: Create backend block for each collection
  lineinfile:
    path: "{{ haproxy_conf }}"
    line: "backend {{ item.path | replace('/', '-') }}"
  with_items: "{{ collections }}"

- name: Create backend block for main catalog &  restrictedAccess
  lineinfile:
    path: "{{ haproxy_conf }}"
    line: "backend {{ item }}"
  with_items:
    - "{{ catalog_backend }}"
    - "{{ restricted_backend }}"

- name: Set cookie persistence for authentication in collection backends
  lineinfile:
    path: "{{ haproxy_conf }}"
    line: "\tcookie JSESSIONID prefix nocache"
    insertafter: "backend {{ item.path | replace('/', '-') }}"
  with_items: "{{ collections }}"

- name: Set cookie persistence for authentication in main catalog's & restrictedAccess backend
  lineinfile:
    path: "{{ haproxy_conf }}"
    line: "\t cookie JSESSIONID prefix nocache"
    insertafter: "backend {{ item }}"
  with_items:
    - "{{ catalog_backend }}"
    - "{{ restricted_backend }}"
