- name: Add worker to the modproxy lb worker
  blockinfile:
    dest: "{{ hostvars[load_balancer].modproxy_conf }}"
    insertafter: <Proxy \"balancer://{{ item }}\">
    marker: '#{mark} {{ item }}:{{ worker.host | default(ansible_hostname) }}:{{ worker.port | default(tomcat_ajp_port) }}'
    block: BalancerMember "ajp://{{ worker.host | default(ansible_hostname) }}:{{ worker.port | default(tomcat_ajp_port) }}" loadfactor={{ worker.loadfactor | default(1) }} route={{ tomcat_name }}
  delegate_to: "{{ load_balancer }}"
  vars:
    ansible_become: "{{ hostvars[load_balancer].ansible_become | default(False) }}" # depends on how httpd was installed
  with_items: "{{ worker.clusters }}"

- name: Add worker to the modproxy restricted worker
  blockinfile:
    dest: "{{ hostvars[load_balancer].modproxy_conf }}"
    insertafter: <Proxy \"balancer://restricted\">
    marker: '#{mark} restricted:{{ worker.host | default(ansible_hostname) }}:{{ worker.port | default(tomcat_ajp_port) }}'
    block: BalancerMember "ajp://{{ worker.host | default(ansible_hostname) }}:{{ worker.port | default(tomcat_ajp_port) }}" loadfactor={{ worker.loadfactor | default(1) }} route={{ tomcat_name }}
  delegate_to: "{{ load_balancer }}"
  vars:
    ansible_become: "{{ hostvars[load_balancer].ansible_become | default(False) }}" # depends on how httpd was installed

- name: Add java melody urimaps
  delegate_to: "{{ load_balancer }}"
  lineinfile:
    path: "{{ hostvars[load_balancer].modproxy_conf }}"
    line: ProxyPass "/monitoring/{{ tomcat_name }}" "http://{{ worker.host | default(ansible_hostname) }}:{{ tds_melody.port }}/{{ tds_context }}/monitoring"
  when: tds_melody is defined
