downloads: "{{ playbook_dir }}/downloads"

tap_build: local
tap_context: udg-tap
tap_baseurl: https://localhost/{{ tap_context }}
tap_managers_email: [manager@company.com]
tap_email_noreply: manager@company.com
tap_tds_baseurl: https://localhost/thredds
